sudo: required
services:
  - docker

before_install:
  - docker build -t radhakrishna1979/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true radhakrishna1979/react-test npm run test -- --coverage

after_success:
  - docker build -t kommera1979/multi-rk-client ./client 
  - docker build -t kommera1979/multi-rk-nginx  ./nginx
  - docker build -t kommera1979/multi-rk-server ./server
  - docker build -t kommera1979/multi-rk-worker ./worker

  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kommera1979/multi-rk-client
  - docker push kommera1979/multi-rk-nginx
  - docker push kommera1979/multi-rk-server
  - docker push kommera1979/multi-rk-worker


  
